### PR TITLE
updated readme

### LINKED ISSUE #35: update readme
@aaryak-shah @kunaljain0212  after the addition of 3rd screen I think we need update the readme file of this repository so can you please assign this to me

### PR DESCRIPTION
**Pull request by AmanPachori**
@hs2361 @aaryak-shah I have updated the readme file fixes #35

### CODE REVIEW

**Comment by AmanPachori** [comment]
@aaryak-shah please review this PR

**Comment by aaryak-shah** [comment]
@AmanPachori there's a few final fixes/changes that were just merged in #34, can you pull the current master and update the screenshots accordingly?

**Comment by AmanPachori** [comment]
@aaryak-shah ok I will do that

**Comment by AmanPachori** [comment]
@aaryak-shah I have done the changes as you requested

**Pull request merged**
