### PR TITLE
Resolved issues in UI

### PR DESCRIPTION
**Pull request by sahil-mittal**
#33 resolved. @hs2361 @aaryak-shah please verify.

### CODE REVIEW

**Comment by aaryak-shah** [comment]
Hey @sahil-mittal great work on the theme switch! There's a few changes still pending:

- The nav menu, while now functional, is still overflowing in mobile view for some screen sizes. My suggestion would be to reduce the gap between the buttons and also reduce their padding or font size. A possibly better alternative would be to make the mobile menu into a vertical list (current tab could be indicated by a bold/green font; button-like outline would be removed for mobile)
- Update the light theme search bar in leaderboard to match the projects page.

**Comment by AmanPachori** [comment]
@aaryak-shah I have update the light theme in search bar in leaderboard so can I also make PR

**Comment by sahil-mittal** [comment]
@AmanPachori I've been already working on this issue as this was assigned to me. Hope you understand.

**Comment by sahil-mittal** [comment]
@aaryak-shah please tell if the underlying ss looks fine?
image

**Pull request merged**
