### PR TITLE
[DOCUMENTATION] Update Readme #14

### PR DESCRIPTION
**Pull request by AmanPachori**
@kunaljain0212  I have update readme file

### CODE REVIEW

**Review by kunaljain0212 — CHANGES_REQUESTED** [review]
Overall great work! I've just left some minor changes.

**Comment by AmanPachori** [comment]
Sure  @kunaljain0212  sir I will makethese changes

**Comment by AmanPachori** [comment]
@kunaljain0212  I have done all the changes that was requested above.

**Comment by kunaljain0212** [comment]
Looks great! Thank you for your contribution.

**Review by kunaljain0212 — APPROVED** [review]

**Pull request merged**
