### PR TITLE
Improve Stats Page

### LINKED ISSUE #30: Fix/Improve Stats Page
- Add a visualisation
- Screen shows undefined stats instead while they are being fetch, and that persists if you lose your internet connection. Add a loading icon or don't display stats till they are completely fetch.
- Side margin is too large in mobile view. Improve responsiveness of the page.

### PR DESCRIPTION
**Pull request by AmanPachori**
@aaryak-shah I have improved the stats page fixes #30

### CODE REVIEW

**Comment by AmanPachori** [comment]
@aaryak-shah Can you please review this PR

**Comment by aaryak-shah** [comment]
@AmanPachori just a few final touches:

Change grammar and spacing on statistics:
- Requests* (with capital letter R)
- Issues* ((with capital letter I)
- remove extra space in Pull Requests statistic

Pull the current master branch and resolve merge conflicts (as the light theme PR has been merged)

**Comment by AmanPachori** [comment]
@aaryak-shah I have done the changes as you requested

**Comment by AmanPachori** [comment]
@aaryak-shah I have also implement the search by roll no. and by score so can you please change the difficulty level of this issue hard

**Comment by aaryak-shah** [comment]
@AmanPachori hey can you make the bar chart black when in light mode? everything else seems fine. I'll mark this PR as hard.

**Comment by AmanPachori** [comment]
@aaryak-shah can you please guide me in this how to do that

**Comment by AmanPachori** [comment]
@aaryak-shah can I change color to green as it will look good to both themes

**Comment by aaryak-shah** [comment]
@AmanPachori dark mode is implemented by means of a .dark-mode class to the document body. You can see how it is used in `Navbar.svelte` and other components. If you aren't able to do figure out the theme system then try the green.

**Comment by AmanPachori** [comment]
@aaryak-shah I have done changes as requested

**Pull request merged**
